import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';

const headers=()=>({'X-CSRF-Token':readFileSync('/tmp/allur-csrf','utf8')});
const stamp=(minutes:number)=>new Date(Date.now()-minutes*60000+5*3600000).toISOString().slice(0,16);

test('equipment readings, alarms, maintenance and real stock consumption survive reload',async({page},testInfo)=>{
  const suffix=String(Date.now()),part='QA-PART-'+suffix,asset='QA-CV-'+suffix,component='QA-MOTOR-'+suffix;
  const taskNote=`QA Замена перегретого двигателя ${component}`,evidence=`QA Акт замены двигателя ${component}`;
  await page.goto('/');await page.getByTestId('nav-scada').click();
  await page.getByRole('button',{name:'Склад и закупки',exact:true}).click();
  await page.locator('summary').filter({hasText:/^Добавить деталь$/}).click();
  let form=page.getByRole('form',{name:'Новая деталь',exact:true});
  await form.getByLabel('Артикул детали',{exact:true}).fill(part);
  await form.getByLabel('Название детали',{exact:true}).fill('QA Двигатель');
  await form.getByLabel('Минимальный запас',{exact:true}).fill('1');
  await form.getByRole('button',{name:'Добавить деталь',exact:true}).click();
  await expect(form.getByRole('status')).toHaveText('Сохранено');
  await page.locator('summary').filter({hasText:/^Учесть приход или расход$/}).click();
  form=page.getByRole('form',{name:'Складская операция',exact:true});
  await form.getByLabel('Деталь на складе',{exact:true}).selectOption(part);
  await form.getByLabel('Количество (расход со знаком минус)',{exact:true}).fill('2');
  await form.getByLabel('Документ и основание движения',{exact:true}).fill('QA Акт инвентаризации 001');
  await form.getByRole('button',{name:'Сохранить движение',exact:true}).click();
  await expect(form.getByRole('status')).toHaveText('Сохранено');
  await page.getByRole('button',{name:'Оборудование',exact:true}).click();
  await page.locator('summary').filter({hasText:/^Добавить оборудование$/}).click();
  form=page.getByRole('form',{name:'Новое оборудование',exact:true});
  await form.getByLabel('Код оборудования',{exact:true}).fill(asset);
  await form.getByLabel('Название оборудования',{exact:true}).fill('QA Конвейер финальной сборки');
  await form.getByLabel('Тип оборудования',{exact:true}).selectOption('conveyor');
  await form.getByRole('button',{name:'Добавить оборудование',exact:true}).click();
  await expect(form.getByRole('status')).toHaveText('Сохранено');
  await page.getByRole('button',{name:new RegExp('QA Конвейер финальной сборки')}).filter({hasText:asset}).click();
  await page.locator('summary').filter({hasText:/^Добавить узел и настроить контроль$/}).click();
  form=page.getByRole('form',{name:'Новый узел',exact:true});
  await form.getByLabel('Код узла',{exact:true}).fill(component);
  await form.getByLabel('Название узла',{exact:true}).fill('QA Мотор привода');
  await form.getByLabel('Родительское оборудование',{exact:true}).selectOption(asset);
  await form.getByLabel('Тип узла',{exact:true}).selectOption('motor');
  await form.getByLabel('Расположение',{exact:true}).selectOption('drive');
  await form.getByLabel('Деталь для замены',{exact:true}).selectOption(part);
  await form.getByLabel('Модель ресурса',{exact:true}).selectOption('hours');
  await form.getByLabel('Номинальный ресурс (часы)',{exact:true}).fill('100');
  await form.getByLabel('Основание: паспорт или регламент',{exact:true}).fill('QA Проверочный регламент');
  await form.getByLabel('Подтверждённый исходный износ, % (пусто — неизвестен)',{exact:true}).fill('85');
  await form.getByRole('button',{name:'Добавить показатель',exact:true}).click();
  await form.getByLabel('Код показателя 1',{exact:true}).fill('temperature_c');
  await form.getByLabel('Название показателя 1',{exact:true}).fill('Температура узла');
  await form.getByLabel('Единица 1',{exact:true}).fill('°C');
  await form.getByLabel('Порог внимания 1',{exact:true}).fill('80');
  await form.getByLabel('Порог аварии 1',{exact:true}).fill('100');
  await form.getByLabel('Гистерезис 1',{exact:true}).fill('5');
  await form.getByRole('button',{name:'Добавить узел',exact:true}).click();
  await expect(form.getByRole('status')).toHaveText('Сохранено');
  await page.locator('summary').filter({hasText:/^Внести измеренные показания$/}).click();
  form=page.getByRole('form',{name:'Показания узла',exact:true});
  await form.getByLabel('Время показания узла',{exact:true}).fill(stamp(60));
  await form.getByLabel('Суммарная наработка, ч',{exact:true}).fill('100');
  await form.getByLabel('Температура узла',{exact:true}).fill('70');
  await form.getByRole('button',{name:'Сохранить показания',exact:true}).click();
  await expect(form.getByRole('status')).toHaveText('Сохранено');
  await form.getByLabel('Время показания узла',{exact:true}).fill(stamp(5));
  await form.getByLabel('Суммарная наработка, ч',{exact:true}).fill('110');
  await form.getByLabel('Температура узла',{exact:true}).fill('105');
  await form.getByRole('button',{name:'Сохранить показания',exact:true}).click();
  await expect(page.getByText('95 %',{exact:true}).first()).toBeVisible();
  await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({animations:'disabled',path:testInfo.outputPath('scada-equipment.png'),fullPage:true});
  await page.getByRole('button',{name:'События узлов',exact:true}).click();
  const alarm=page.getByRole('row').filter({hasText:'Температура узла'}).filter({hasText:component});
  await alarm.getByRole('button',{name:'Принять в работу'}).click();
  await expect(alarm.getByText('В работе',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'ТО и ресурс',exact:true}).click();
  await page.locator('summary').filter({hasText:/^Запланировать обслуживание$/}).click();
  form=page.getByRole('form',{name:'Новая работа ТО',exact:true});
  await form.getByLabel('Узел для обслуживания',{exact:true}).selectOption(component);
  await form.getByLabel('Плановая дата ТО',{exact:true}).fill('2026-10-07');
  await form.getByLabel('Основание работы',{exact:true}).fill(taskNote);
  const createResponse=page.waitForResponse(response=>response.request().method()==='POST'&&response.url().endsWith('/api/scada/tasks'));
  await form.getByRole('button',{name:'Запланировать ТО',exact:true}).click();
  const created=await createResponse;expect(created.ok()).toBeTruthy();
  const task=await created.json();expect(task).toMatchObject({component_id:component,note:taskNote,status:'planned'});
  await expect(form.getByRole('status')).toHaveText('Сохранено');
  await page.locator('details').filter({has:page.locator(`form[aria-label="Выполнение ТО ${component}"]`)}).locator('summary').click();
  form=page.getByRole('form',{name:'Выполнение ТО '+component,exact:true});
  await form.getByLabel('Акт выполненной работы',{exact:true}).fill(evidence);
  const completeResponse=page.waitForResponse(response=>response.request().method()==='POST'&&response.url().endsWith(`/api/scada/tasks/${task.id}/complete`));
  await form.getByRole('button',{name:'Завершить ТО и списать деталь'}).click();
  const completed=await completeResponse;expect(completed.ok()).toBeTruthy();
  expect(await completed.json()).toMatchObject({id:task.id,component_id:component,status:'done',completion:{evidence}});
  await expect(page.locator('article.scada-entry').filter({hasText:taskNote})).toHaveCount(0);
  await page.reload();await page.getByTestId('nav-scada').click();await page.getByRole('button',{name:'Оборудование',exact:true}).click();
  await page.getByRole('button',{name:'Склад и закупки',exact:true}).click();
  const stock=page.getByRole('row').filter({hasText:part}).first();
  await expect(stock.getByRole('cell').nth(1)).toContainText('1 шт.');
  await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({animations:'disabled',path:testInfo.outputPath('scada-stock.png'),fullPage:true});
  await page.locator('summary').filter({hasText:/^Журнал движения деталей/}).click();
  const movement=page.getByRole('row').filter({hasText:part}).filter({hasText:evidence});
  await expect(movement).toHaveCount(1);
  await expect(movement).toContainText('-1 ед.');await expect(movement).toContainText('Остаток 1');
  await page.getByRole('button',{name:'ТО и ресурс',exact:true}).click();
  await expect(page.locator('article.scada-entry').filter({hasText:taskNote})).toHaveCount(0);
  await page.getByRole('button',{name:'Показать завершённые',exact:true}).click();
  await expect(page.locator('article.scada-entry').filter({hasText:taskNote}).getByText('Выполнено',{exact:true})).toBeVisible();
  await page.locator('summary').filter({hasText:/^Полный журнал ТО/}).click();
  const history=page.getByRole('row').filter({hasText:component}).filter({hasText:taskNote});
  await expect(history).toHaveCount(1);await expect(history).toContainText('Выполнено');
  await page.getByRole('button',{name:'События узлов',exact:true}).click();
  await expect(page.getByRole('row').filter({hasText:'Температура узла'}).filter({hasText:component}).getByText('В работе',{exact:true})).toBeVisible();
});

test('supplier order and partial delivery require real confirmation and receipt',async({page,request})=>{
  const part='QA-ORDER-'+Date.now();
  expect((await request.post('/api/scada/parts',{headers:headers(),data:{id:part,name:'QA Редуктор',minimum:1}})).ok()).toBeTruthy();
  await page.goto('/');await page.getByTestId('nav-scada').click();await page.getByRole('button',{name:'Склад и закупки',exact:true}).click();
  await page.locator('summary').filter({hasText:/^Добавить предложение поставщика$/}).click();
  let form=page.getByRole('form',{name:'Предложение поставщика',exact:true});
  await form.getByLabel('Деталь в предложении',{exact:true}).selectOption(part);
  await form.getByLabel('Поставщик',{exact:true}).fill('QA Поставщик');
  await form.getByLabel('Цена за единицу',{exact:true}).fill('125000.25');
  await form.getByLabel('Поставка, рабочих дней',{exact:true}).fill('3');
  await form.getByLabel('Предложение действует до',{exact:true}).fill('2099-12-31');
  await form.getByLabel('Номер предложения или источник цены',{exact:true}).fill('QA КП-001');
  await form.getByRole('button',{name:'Сохранить предложение'}).click();
  await expect(form.getByRole('status')).toHaveText('Сохранено');
  await page.locator('summary').filter({hasText:/^Создать заявку на закупку$/}).click();
  form=page.getByRole('form',{name:'Новая заявка',exact:true});
  const offers=await form.getByLabel('Предложение для закупки').locator('option').allTextContents();
  await form.getByLabel('Предложение для закупки').selectOption({label:offers.find(o=>o.includes(part))!});
  await form.getByLabel('Количество в заявке',{exact:true}).fill('2');
  await form.getByRole('button',{name:'Создать черновик заявки'}).click();
  await expect(form.getByRole('status')).toHaveText('Сохранено');
  const order=page.locator('article.scada-entry').filter({hasText:part});
  form=order.getByRole('form',{name:/Подтверждение заявки/});
  await form.getByLabel('Документ подтверждения поставщика').fill('QA Подтверждение 001');
  await form.getByRole('button',{name:'Учесть подтверждение поставщика'}).click();
  form=order.getByRole('form',{name:/Приёмка заявки/});
  await form.getByLabel('Фактически получено').fill('1');await form.getByLabel('Номер накладной').fill('QA Накладная 001');
  await form.getByRole('button',{name:'Принять на склад'}).click();
  await expect(form.getByRole('status')).toHaveText('Сохранено');
  const stock=page.getByRole('row').filter({hasText:part}).first();
  await expect(stock.getByRole('cell').nth(1)).toContainText('1 шт.');
  await expect(stock.getByRole('cell').nth(4)).toHaveText('1');
});

test('conveyor topology is configurable and fits mobile while original overview remains',async({page,request},testInfo)=>{
  const asset='QA-TEMPLATE-'+Date.now();
  expect((await request.post('/api/scada/assets',{headers:headers(),data:{id:asset,name:'QA Схема конвейера',kind:'conveyor'}})).ok()).toBeTruthy();
  expect((await request.post(`/api/scada/assets/${asset}/template`,{headers:headers(),data:{}})).ok()).toBeTruthy();
  await page.goto('/');await page.getByTestId('nav-scada').click();
  await page.getByRole('button',{name:'Оборудование',exact:true}).click();
  await page.getByRole('button',{name:/QA Схема конвейера/}).filter({hasText:asset}).click();
  await page.getByRole('button',{name:'Двигатель привода',exact:true}).click();
  await page.locator('summary').filter({hasText:/^Настройки этого узла$/}).click();
  const form=page.getByRole('form',{name:'Настройки узла',exact:true});
  await form.getByLabel('Модель ресурса',{exact:true}).selectOption('hours');
  await form.getByLabel('Номинальный ресурс (часы)',{exact:true}).fill('10000');
  await form.getByLabel('Основание: паспорт или регламент',{exact:true}).fill('QA Паспорт привода 001');
  await form.getByLabel('Подтверждённый исходный износ, % (пусто — неизвестен)',{exact:true}).fill('0');
  await form.getByRole('button',{name:'Сохранить настройки узла',exact:true}).click();
  await expect.poll(async()=>{const r=await request.get('/api/scada');return (await r.json()).components.find((c:{id:string})=>c.id===asset+'-motor')?.rated_life;}).toBe(10000);
  await page.locator('summary').filter({hasText:/^Настройки этого узла$/}).click();
  await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({animations:'disabled',path:testInfo.outputPath('scada-conveyor.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBeTruthy();
  await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({animations:'disabled',path:testInfo.outputPath('scada-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});await page.getByTestId('nav-overview').click();
  await expect(page.getByRole('heading',{name:'Обзор производства',exact:true})).toBeVisible();
  await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({animations:'disabled',path:testInfo.outputPath('overview-preserved.png'),fullPage:true});
});

