import {useState, type FormEvent} from 'react';
import {date, number, post} from './api';
import type {Act, Component, Forecast, State} from './EmulationTypes';

export function ForecastWindow({forecast}:{forecast:Forecast}){
  if(forecast.open_ended)return <>Позже {forecast.after?new Date(forecast.after).toLocaleDateString('ru-RU',{timeZone:'Asia/Qyzylorda'}):'горизонта расчёта'}</>;
  if(!forecast.from||!forecast.to)return <>Нет оценки даты</>;
  const day=(d:string)=>new Date(d).toLocaleDateString('ru-RU',{timeZone:'Asia/Qyzylorda'});
  return <>{day(forecast.from)} — {day(forecast.to)}</>;
}

export function EmulationMaintenance({data,disabled,act,inspect}:{data:State;disabled:boolean;act:Act;inspect:(c:Component)=>void}){
  const [filter,setFilter]=useState('soon');
  const rows=data.components.filter(c=>filter==='all'||filter==='soon'&&(c.level!=='ok'||c.remaining_hours!==null&&c.remaining_hours<=90*16)||c.robot===filter).sort((a,b)=>(a.remaining_hours??Infinity)-(b.remaining_hours??Infinity));
  return <section className="panel" id="emu-maintenance" data-testid="emulation-maintenance"><div className="panel-heading"><div><span className="eyebrow">Учебная модель · календарь 2 × 8 ч, Пн–Пт</span><h2>ТО и прогноз стенда</h2></div><span className="subtle-pill">{data.summary.maintenance_30d} работ в 30 рабочих дней</span></div>
    <p className="intro">Срок пересчитывается по текущей нагрузке, температуре, циклам и смазке. Диапазон ±20% показывает условную погрешность учебной модели. Это оценка ресурса, а не гарантированная дата отказа.</p>
    <div className="automation-tabs" role="group" aria-label="Фильтр прогноза стенда">{[['soon','Ближайшие 90 рабочих дней'],['all','Все узлы'],['R1','R1'],['R2','R2'],['R3','R3'],['R4','R4'],['CV','Конвейер']].map(([key,label])=><button key={key} className={`button ${filter===key?'primary':'secondary'} compact`} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}</button>)}</div>
    <div className="robot-table"><table><thead><tr><th>Узел</th><th>Износ</th><th>Ресурс</th><th>Окно обслуживания</th><th>Основа расчёта</th><th>Учебная работа</th></tr></thead><tbody>{rows.map(c=>{const p=data.parts.find(p=>p.id===c.part);return <tr key={c.id} data-testid={`emulation-forecast-${c.id}`}><td><button className="button secondary compact" onClick={()=>inspect(c)}>{c.robot} · {c.name}</button><small className="scada-subtext">{c.id}</small></td><td>{number(c.wear_pct,1)}%<meter min="0" max="100" value={Math.min(100,c.wear_pct)} aria-label={`Износ ${c.id}`}/></td><td>{number(c.remaining_hours,1)} ч<small className="scada-subtext">{number(c.forecast.working_days,1)} рабочих дней</small></td><td><ForecastWindow forecast={c.forecast}/></td><td>{c.forecast.basis}</td><td><button className="button secondary compact" disabled={disabled||!p||!p.service&&p.stock<1} onClick={()=>void act('replace',{target:c.id})}>{p?.service?'Учебное ТО':'Учебная замена'}: {c.id}</button>{p&&!p.service&&<small className="scada-subtext">На учебном складе: {p.stock}</small>}</td></tr>;})}</tbody></table></div>
    {!rows.length&&<p className="small-note">В выбранном горизонте работ нет.</p>}
    <details><summary>Как считается износ и прогноз</summary><ul className="emu-model-list"><li>Редукторы: базовый ресурс 6 000 ч с поправкой на скорость и нагрузку в степени 10/3. Нагрузка +30% ускоряет расход ресурса примерно в 2,4 раза.</li><li>Двигатели: старение изоляции относительно 40 000 ч при 80 °C; каждые +10 °C удваивают скорость старения.</li><li>Тормоза, кабели и оснастка: срабатывания и изгибы за производственный цикл. Батарея, вентилятор и калибровка: календарная наработка.</li><li>Конвейер: сопротивление роликов повышает нагрузку привода; недостаток смазки ускоряет вытяжку цепи. Предельная вытяжка в модели — 3%.</li><li>Даты используют модельное время, 16 рабочих часов в день и пятидневную неделю. Прогноз далёких замен ограничен отображаемым горизонтом.</li><li>Предупреждение датчика требует внимания независимо от расчётного остаточного ресурса. Пороговые значения стенда не являются настройками реального контроллера.</li></ul></details>
  </section>;
}

export function EmulationStock({data,disabled,act}:{data:State;disabled:boolean;act:Act}){
  const [completed,setCompleted]=useState(false),orders=data.orders.filter(o=>completed||o.status==='in_transit');
  return <section className="panel" id="emu-stock" data-testid="emulation-stock"><div className="panel-heading"><div><span className="eyebrow">Учебный каталог из SCADA-стенда</span><h2>Учебный склад</h2></div><button className="button secondary" disabled={disabled||!data.parts.some(p=>p.deficit>0)} onClick={()=>void act('order_all')}>Заказать весь учебный дефицит</button></div>
    <p className="intro">Потребность на 90 рабочих дней учитывает минимальный запас и поставки в пути. Компании, артикулы и цены каталога вымышлены. Заказ и его прибытие рассчитываются внутри стенда по модельному времени; внешнему поставщику ничего не отправляется.</p>
    <div className="robot-table"><table><thead><tr><th>Деталь</th><th>На складе / минимум</th><th>Нужно / в пути</th><th>Дефицит</th><th>Учебное предложение</th><th>Действие</th></tr></thead><tbody>{data.parts.filter(p=>!p.service).map(p=><tr key={p.id} data-testid={`emulation-part-${p.id}`}><td>{p.name}<small className="scada-subtext">{p.id}</small></td><td>{number(p.stock)} / {p.minimum}</td><td>{p.needed_90d} / {p.in_transit}</td><td>{p.deficit}</td><td>{p.recommended_offer?<><strong>{p.recommended_offer.supplier}</strong><small className="scada-subtext">{number(p.recommended_offer.price_kzt)} ₸ · {p.recommended_offer.lead_workdays} рабочих дней</small><small className="scada-subtext">{p.recommended_offer.reason}</small></>:'Нет предложения'}<details><summary>Сравнить предложения</summary>{p.offers.map(o=><p key={o.supplier_id} className="small-note">{o.supplier} — {number(o.price_kzt)} ₸, {o.lead_workdays} рабочих дней</p>)}</details></td><td><button className="button secondary compact" disabled={disabled||p.deficit<1||!p.recommended_offer} onClick={()=>void act('order',{target:p.id})} aria-label={`Учебный заказ: ${p.name}`}>Заказать {p.deficit>0?p.deficit:'—'} шт.</button></td></tr>)}</tbody></table></div>
    <details><summary>Услуги учебного каталога</summary>{data.parts.filter(p=>p.service).map(p=><div className="scada-entry" key={p.id}><strong>{p.name}</strong><p className="small-note">{p.offers.map(o=>`${o.supplier}: ${number(o.price_kzt)} ₸`).join(' · ')}</p><p className="small-note">Услуга отмечается кнопкой «Учебное ТО» у компонента, складской заказ для неё не создаётся.</p></div>)}</details>
    <div className="panel-heading emu-subheading"><h3>Поставки стенда</h3><button className="button secondary compact" aria-pressed={completed} onClick={()=>setCompleted(!completed)}>{completed?'Только в пути':'Показать полученные поставки'}</button></div>
    {!orders.length?<p className="small-note">Учебных заказов в выбранном списке нет.</p>:<div className="robot-table"><table><thead><tr><th>Заказ</th><th>Количество / сумма</th><th>Учебный поставщик</th><th>Ожидается в модели</th><th>Состояние</th></tr></thead><tbody>{orders.map(o=><tr key={o.id} data-testid={`emulation-order-${o.id}`}><td>{data.parts.find(p=>p.id===o.part)?.name??o.part}<small className="scada-subtext">{o.id}</small></td><td>{o.quantity} шт. · {number(o.total_kzt)} ₸</td><td>{o.supplier}<small className="scada-subtext">{o.reason}</small></td><td>{date(o.eta)}<small className="scada-subtext">{o.lead_workdays} рабочих дней</small></td><td>{o.status==='received'?'Получено на учебный склад':'В пути по модели'}{o.received_at&&<small className="scada-subtext">{date(o.received_at)}</small>}</td></tr>)}</tbody></table></div>}
  </section>;
}

type AssistantAction={action:string;target?:string;label:string};
type Answer={engine:'rules';source:'emulation';text:string;actions:AssistantAction[];revision:number};
type Message={id:number;question:string;answer:Answer};
const prompts=['Что требует замены?','Прогноз отказов','Какие нагрузки по осям?','Почему стоит линия?','Что с конвейером?','Чего не хватает на складе?','Где купить детали?','Закажи всё недостающее','Отправь сводку'];
export function EmulationAssistant({data,disabled,act}:{data:State;disabled:boolean;act:Act}){
  const [question,setQuestion]=useState(''),[messages,setMessages]=useState<Message[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState<Record<string,boolean>>({});
  async function ask(q:string){if(!q.trim()||busy)return;setBusy(true);setError('');try{const answer=await post<Answer>('/emulation/assistant',{question:q.trim()});setMessages(m=>[...m,{id:Date.now(),question:q.trim(),answer}].slice(-30));setQuestion('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function submit(e:FormEvent){e.preventDefault();void ask(question);}
  return <section className="panel" id="emu-assistant"><div className="panel-heading"><div><span className="eyebrow">Детерминированные правила · данные эмуляции</span><h2>Учебный ассистент</h2></div><span className="subtle-pill">БЕЗ LLM</span></div>
    <p className="intro">Помощник отвечает по фактическому состоянию виртуального стенда: ресурс, нагрузки, аварии, выпуск, склад и предложения. Это перенесённый помощник на правилах из архива. Предложенные изменения выполняются только после нажатия кнопки подтверждения.</p>
    <div className="emu-prompts">{prompts.map(q=><button key={q} className="button secondary compact" disabled={busy} onClick={()=>void ask(q)}>{q}</button>)}</div>
    <div className="emu-chat" data-testid="emulation-chat" aria-live="polite">{!messages.length&&<p className="small-note">Задайте вопрос, например «Что требует замены на R2?» или «Нагрузка конвейера».</p>}{messages.map(m=><article key={m.id} className="emu-message"><strong>Вы: {m.question}</strong><p className="emu-answer">{m.answer.text}</p>{m.answer.revision!==data.revision&&<small className="scada-subtext">Ответ рассчитан для состояния № {m.answer.revision}; стенд с тех пор изменился. Команда проверит актуальную потребность.</small>}{m.answer.actions.map((a,j)=>{const key=`${m.id}:${j}`;return <button key={key} className="button secondary compact" disabled={disabled||!!done[key]} onClick={async()=>{if(await act(a.action,a.target?{target:a.target}:{}))setDone(d=>({...d,[key]:true}));}}>{done[key]?'Команда выполнена':`Подтвердить: ${a.label}`}</button>;})}</article>)}</div>
    <form className="emu-chat-form" aria-label="Вопрос учебному ассистенту" onSubmit={submit}><label>Вопрос по данным стенда<input aria-label="Вопрос по данным стенда" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={1000} required placeholder="Что с роботом R1?"/></label><button className="button primary" disabled={busy||!question.trim()}>{busy?'Анализируем данные…':'Спросить ассистента'}</button></form>
    {error&&<p className="inline-error" role="alert">{error}</p>}{messages.length>0&&<button className="button secondary compact" onClick={()=>{setMessages([]);setDone({});}}>Очистить беседу на этом экране</button>}
  </section>;
}

const channels:Record<string,string>={alarms:'Аварии',maintenance:'ТО и ресурс',stock:'Учебный склад',summary:'Сводки'};
export function EmulationNotifications({data,disabled,act}:{data:State;disabled:boolean;act:Act}){
  const [unread,setUnread]=useState(false),notes=data.notifications.filter(n=>!unread||!n.read&&n.status==='recorded');
  return <section className="panel" id="emu-notifications" data-testid="emulation-notifications"><div className="panel-heading"><div><span className="eyebrow">Внутренний журнал виртуального стенда</span><h2>Уведомления стенда</h2></div><span className="subtle-pill">{data.notifications.filter(n=>!n.read&&n.status==='recorded').length} непрочитанных</span></div>
    <p className="intro">Уведомления сохраняются в приложении. Внешняя отправка отсутствует. Настройки категорий и отметка прочтения общие для операторов этой установки.</p>
    <div className="emu-preferences">{Object.entries(data.channels).map(([key,active])=><label key={key}><input type="checkbox" checked={active} disabled={disabled} onChange={e=>void act('channel',{target:key,active:e.target.checked})}/>{channels[key]??key}</label>)}</div>
    <div className="robot-actions"><button className="button secondary compact" disabled={disabled} onClick={()=>void act('summary')}>Создать внутреннюю сводку</button><button className="button secondary compact" disabled={disabled||!data.notifications.some(n=>!n.read&&n.status==='recorded')} onClick={()=>void act('notification_read_all')}>Прочитать все уведомления стенда</button><button className="button secondary compact" aria-pressed={unread} onClick={()=>setUnread(!unread)}>{unread?'Показать все уведомления':'Только непрочитанные'}</button></div>
    {!notes.length&&<p className="small-note">В выбранном списке уведомлений нет.</p>}<div className="emu-notifications">{notes.map(n=><article className={`scada-entry ${n.read?'':'emu-unread'}`} key={n.id} data-testid={`emulation-notification-${n.id}`}><small className="scada-subtext">{number(n.t,2)} ч модели · {channels[n.channel]??n.channel} · {n.status==='muted'?'Категория отключена':'Записано в приложении'}</small><p>{n.text}</p>{!n.read?<button className="button secondary compact" disabled={disabled} onClick={()=>void act('notification_read',{target:String(n.id)})}>Прочитано: уведомление {n.id}</button>:<small className="scada-subtext">Прочитано оператором</small>}</article>)}</div>
  </section>;
}
