import {useState} from 'react';
import {post,number} from './api';
import {useCanWrite} from './permissions';
import {useLive} from './Manufacturing';
import type {AutomationData} from './Automation';

type AIStatus = {ready:boolean;model:string;local_only:boolean;message:string};
type AIAnswer = {model:string;analysis:string;action:string;reason:string;data_source?:'plant'|'emulation';proposal:{id:string;robot_id:string}|null;maintenance_facts?:{shortages:{id:string;name:string;stock:number;needed:number;on_order:number;deficit:number}[]};emulation_facts?:{model_time:string;component_count:number;components:{id:string}[];shortage_count:number;shortages:{id:string;name:string;stock:number;needed_90d:number;in_transit:number;deficit:number}[]}};

export function LocalAI() {
  const canWrite = useCanWrite();
  const status = useLive<AIStatus>('/ai/status',15000), robots = useLive<AutomationData>('/automation',10000);
  const [question,setQuestion] = useState('Проанализируй качество, выполнение плана и простои. Укажи подтверждённые проблемы и недостающие данные.');
  const [robot,setRobot] = useState(''), [allowCommand,setAllowCommand] = useState(false);
  const [source,setSource] = useState<'plant'|'emulation'>('plant');
  const [answer,setAnswer] = useState<AIAnswer|null>(null), [busy,setBusy] = useState(false), [error,setError] = useState('');
  return <div className="manufacturing-page"><section className="panel ai-hero"><span className="eyebrow">Локальный ИИ · данные остаются в установке клиента</span><h2>Анализ и предложения оператору</h2><p>{status.value?.message??'Проверяем локальную модель…'}</p><span className={`connection-tag ${status.value?.ready?'fresh':''}`}>{status.value?.model??'Локальная модель'} · {status.value?.ready?'готова':'не готова'}</span><p className="intro">ИИ читает текущие показания, отчёт кейса и записи качества. Он объясняет проблемы и может подготовить команду выбранному роботу. Отправка физическому оборудованию требует отдельного подтверждения в разделе «Автоматизация» и проверок контроллера.</p>
      <p className="intro">Также доступны узлы конвейера, оценки ресурса, события и дефициты деталей. Выберите фактические данные или эмуляцию SCADA. Данные учебного стенда передаются модели только при явном выборе этого источника.</p><div className="automation-tabs">{(source==='emulation'?['Почему остановилась учебная линия и какие аварии требуют внимания?', 'Какие узлы учебного стенда скоро потребуют замены?', 'Каких деталей не хватает на учебном складе и какие поставщики подходят?']:['Какие узлы требуют обслуживания и каких данных не хватает?', 'Каких запчастей не хватает и какие предложения поставщиков подходят?']).map(q=><button type="button" className="button secondary compact" key={q} disabled={busy} onClick={()=>setQuestion(q)}>{q}</button>)}</div>
      <form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setAnswer(null);try{setAnswer(await post<AIAnswer>('/ai/analyze',{question,robot_id:robot||null,allow_command:source==='plant'&&allowCommand,data_source:source}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}} className="ai-form">
        <label>Источник данных ИИ<select value={source} disabled={busy} onChange={e=>{const next=e.target.value as 'plant'|'emulation';setSource(next);setRobot('');setAllowCommand(false);setAnswer(null);setError('');setQuestion(next==='emulation'?'Проанализируй состояние учебного стенда, аварии, прогноз обслуживания и дефициты запчастей.':'Проанализируй качество, выполнение плана и простои. Укажи подтверждённые проблемы и недостающие данные.');}}><option value="plant">Фактические данные</option><option value="emulation">Эмуляция SCADA</option></select></label>
        <label>Робот для анализа<select value={robot} disabled={busy} onChange={e=>{setRobot(e.target.value);setAllowCommand(false);}}><option value="">{source==='emulation'?'Весь учебный стенд':'Общий анализ производства'}</option>{source==='emulation'?['R1','R2','R3','R4','CV'].map(id=><option key={id} value={id}>{id==='CV'?'CV · Учебный конвейер':`${id} · Учебный робот`}</option>):robots.value?.robots.map(r=><option key={r.robot_id} value={r.robot_id}>{r.robot_id} · {r.line_section}</option>)}</select></label>
        <label>Вопрос локальному ИИ<textarea rows={5} required minLength={3} maxLength={2000} value={question} onChange={e=>setQuestion(e.target.value)} disabled={!canWrite||busy}/></label>
        {source==='plant'?<label className="ai-permission"><input type="checkbox" checked={allowCommand} disabled={!robot||!canWrite||busy} onChange={e=>setAllowCommand(e.target.checked)}/> Разрешаю подготовить предложение команды выбранному роботу</label>:<p className="report-warning">Учебный режим: показания рассчитаны эмулятором, поставщики и цены вымышлены. Физические команды в этом режиме недоступны. Учебные действия выполняются в разделе «Оборудование и ТО → Эмуляция».</p>}
        <button className="button primary" disabled={!canWrite||busy||!status.value?.ready}>{busy?'Модель анализирует данные…':'Выполнить локальный анализ'}</button>
      </form><p className="small-note">Ответ на CPU может занять до 150 секунд. Вывод модели нужно сверить с показаниями; он не является прогнозом поломки или разрешением на обход защиты.</p>
      {(error||status.error)&&<p role="alert" className="inline-error">{error||status.error}</p>}
      {answer?.emulation_facts&&<section aria-label="Данные эмуляции для ИИ"><h3>Учебный стенд на момент запроса</h3><p className="small-note">Модельное время: {new Date(answer.emulation_facts.model_time).toLocaleString('ru-RU',{timeZone:'Asia/Qyzylorda'})}. В анализ передано {answer.emulation_facts.components.length} приоритетных узлов из {answer.emulation_facts.component_count}; дефицитных позиций в стенде: {answer.emulation_facts.shortage_count}. Значения ниже рассчитаны сервером.</p>{answer.emulation_facts.shortages.length>0&&<div className="robot-table"><table><thead><tr><th>Артикул</th><th>Учебная деталь</th><th>Остаток</th><th>Нужно на 90 рабочих дней</th><th>В пути</th><th>Дефицит</th></tr></thead><tbody>{answer.emulation_facts.shortages.map(p=><tr key={p.id}><td>{p.id}</td><td>{p.name}</td><td>{number(p.stock)}</td><td>{number(p.needed_90d)}</td><td>{number(p.in_transit)}</td><td>{number(p.deficit)}</td></tr>)}</tbody></table></div>}</section>}
      {!!answer?.maintenance_facts?.shortages.length&&<section><h3>Дефициты по данным учёта на момент запроса</h3><p className="small-note">Эти значения рассчитаны сервером. При расхождении с текстом ИИ проверяйте данные учёта.</p><div className="robot-table"><table><thead><tr><th>Артикул</th><th>Деталь</th><th>Остаток</th><th>Нужно для ТО</th><th>В заказе</th><th>Дефицит</th></tr></thead><tbody>{answer.maintenance_facts.shortages.map(p=><tr key={p.id}><td>{p.id}</td><td>{p.name}</td><td>{number(p.stock)}</td><td>{number(p.needed)}</td><td>{number(p.on_order)}</td><td>{number(p.deficit)}</td></tr>)}</tbody></table></div></section>}
      {answer&&<article className="ai-answer" aria-label="Ответ локального ИИ"><span className="eyebrow">{answer.model} · локальный ответ</span><p>{answer.analysis}</p><p><strong>Основание:</strong> {answer.reason}</p>{answer.proposal?<p className="report-warning">Создано предложение {answer.proposal.id} для {answer.proposal.robot_id}. Оно ещё не отправлено оборудованию. Проверьте его в разделе «Автоматизация».</p>:<p className="intro">Команды оборудованию не создавались.</p>}</article>}
    </section><section className="panel"><h2>Как проходит команда</h2><ol className="ai-flow"><li>Показания и состояние поступают от заводского шлюза.</li><li>Локальная модель предлагает действие в пределах разрешённого списка.</li><li>Оператор проверяет робота, действие и основание.</li><li>Система повторно проверяет свежесть данных, режим контроллера, защиту и срок команды.</li><li>Шлюз проверяет местные блокировки и возвращает подтверждённый результат. При неизвестном результате повторное выполнение блокируется.</li></ol><p className="intro">Модель не получает ключи шлюза и не пишет напрямую в контроллер. Аварийная остановка и аппаратные блокировки работают независимо от приложения.</p></section></div>;
}
