import {useRef, useState, type ReactNode, type FormEvent} from 'react';
import {date, number, post, request} from './api';
import {useLive} from './Manufacturing';
import {useCanWrite} from './permissions';
import {Emulation} from './Emulation';

type Operation = 'welding'|'painting'|'assembly'|'unknown';
const operationNames:Record<Operation,string>={welding:'Сварка',painting:'Окраска',assembly:'Сборка',unknown:'Не определено'};
const operationOptions=[{id:'auto',name:'Определять по роботу или названию участка'},...Object.entries(operationNames).map(([id,name])=>({id,name}))];
type Asset = {operation:Operation;operation_configured:Operation|null;operation_source:string;revision:number;id:string;name:string;kind:string;section:string;robot_id:string|null;severity:string;component_count:number};
type Rule = {metric:string;label:string;unit:string;direction:string;warning:number;alarm:number;hysteresis:number};
type Reading = {record_id:string;component_id:string;timestamp:string;metrics:Record<string,number>;runtime_hours:number|null;total_cycles:number|null;distance_km:number|null};
type Component = {id:string;asset_id:string;name:string;node:string;kind:string;part_id:string|null;part_quantity:number;life_model:string;rated_life:number|null;wear_pct:number|null;remaining_hours:number|null;due_date:string|null;gaps:string[];connection:string;severity:string;last:Reading|null;thresholds:Rule[];specification:string;active_alarms:Record<string,string>;revision:number;initial_wear_pct:number|null;reference_temperature_c:number;commissioned_at:string|null;expected_interval_seconds:number;robot_metric_map:Record<string,string>};
type Recommendation = {offer_id:string;supplier:string;currency:string;price_minor:number;lead_workdays:number;reason:string};
type Part = {scope_needed?:number;id:string;name:string;unit:string;stock:number;minimum:number;needed:number;on_order:number;deficit:number;recommendations:Recommendation[]};
type Offer = {id:string;part_id:string;supplier:string;currency:string;price_minor:number;lead_workdays:number;valid_until:string};
type Order = {id:string;part_id:string;supplier:string;currency:string;price_minor:number;quantity:number;received:number;status:string;eta:string|null};
type Task = {id:string;component_id:string;due_date:string;note:string;status:string;completed_by?:string;completed_at?:string};
type Alarm = {id:string;component_id:string;component_name:string;label:string;severity:string;value:number;opened_at:string;last_seen:string;status:string;acknowledged_at:string|null;recovered_at:string|null};
type Calendar = {hours_per_day:number;weekdays:number[];holidays:string[]};
type ScadaData = {scope?:{operation:Operation;inventory:string;inventory_note:string};part_catalog?:{id:string;name:string}[];assets:Asset[];components:Component[];parts:Part[];offers:Offer[];orders:Order[];tasks:Task[];alarms:Alarm[];calendar:Calendar;totals:{assets:number;components:number;alarms:number;shortages:number}};
type Journal = {total:number;rows:Record<string,unknown>[];offset:number};
const status:Record<string,string> = {ok:'Норма',warning:'Внимание',alarm:'Авария',unknown:'Нет свежих данных',missing:'Нет показаний',stale:'Устарели',fresh:'Свежие данные',open:'Открыто',acknowledged:'В работе',recovered:'Причина устранена',closed:'Закрыто',draft:'Черновик',ordered:'Ожидается поставка',received:'Получено',cancelled:'Отменено',planned:'Запланировано',done:'Выполнено'};
const models:Record<string,string> = {none:'Без расчёта ресурса',hours:'Наработка, часы',cycles:'Количество циклов',distance:'Пробег, км',thermal:'Температурное старение двигателя',reducer:'Редуктор: нагрузка и скорость',chain:'Цепь: нагрузка и смазка',calendar:'Календарный интервал, дни'};
const kinds:Record<string,string> = {motor:'Двигатель',reducer:'Редуктор',brake:'Тормоз',cable:'Кабельный пакет',battery:'Батарея',fan:'Вентилятор',tool:'Оснастка',chain:'Цепь',lubricator:'Лубрикатор',sensor:'Датчик',other:'Другой узел'};
const nodeNames:Record<string,string> = {drive:'Привод',chain:'Цепь и настил',take:'Натяжная станция',track:'Позиционирование',cable:'Кабели',tool:'Оснастка',ctrl:'Шкаф управления'};
const txt = (f:FormData,k:string) => String(f.get(k)??'').trim();
const num = (f:FormData,k:string) => Number(txt(f,k));
const nullable = (f:FormData,k:string) => txt(f,k)===''?null:num(f,k);
const uid = () => Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');
const day = (s:string|null|undefined) => s?new Date(s+'T12:00:00+05:00').toLocaleDateString('ru-RU'):'—';
const localNow = () => {const now=new Date();return new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,16);};

function Badge({value}:{value:string}) {return <span className={`scada-status ${value}`}>{status[value]??value}</span>;}
function Input({title,name,type='text',required=false,min,max,step,defaultValue}:{title:string;name:string;type?:string;required?:boolean;min?:number|string;max?:number;step?:string;defaultValue?:string|number}) {
  return <label>{title}<input aria-label={title} name={name} type={type} required={required} min={min} max={max} step={step} defaultValue={defaultValue} maxLength={type==='text'?500:undefined}/></label>;
}
function Select({title,name,items,empty=false,defaultValue}:{title:string;name:string;items:{id:string;name:string}[];empty?:boolean;defaultValue?:string}) {
  return <label>{title}<select aria-label={title} name={name} required={!empty} defaultValue={defaultValue}>{empty&&<option value="">Не задано</option>}{items.map(i=><option key={i.id} value={i.id}>{i.name} · {i.id}</option>)}</select></label>;
}
function SaveForm({title,button,children,submit,changed,reset=true}:{title:string;button:string;children:ReactNode;submit:(f:FormData,id:string)=>Promise<unknown>;changed:()=>void;reset?:boolean}) {
  const canWrite=useCanWrite(), [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const identity=useRef(uid());
  async function save(event:FormEvent<HTMLFormElement>) {
    event.preventDefault();const form=event.currentTarget;if(!canWrite||busy)return;
    setBusy(true);setError('');setMessage('');
    try {await submit(new FormData(form),identity.current);identity.current=uid();if(reset)form.reset();setMessage('Сохранено');changed();}
    catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }
  return <form aria-label={title} onSubmit={save} className="scada-form"><fieldset disabled={!canWrite||busy}><legend>{title}</legend><div className="quality-form">{children}</div><button className="button primary" disabled={!canWrite||busy}>{busy?'Сохраняем…':button}</button></fieldset>{error&&<p role="alert" className="inline-error">{error}</p>}{message&&<p role="status" className="small-note">{message}</p>}</form>;
}

export function ScadaPage({operation}:{operation?:Exclude<Operation,'unknown'>}={}) {
  const live=useLive<ScadaData>(`/scada${operation?`?operation=${operation}`:''}`),[tab,setTab]=useState(operation?'equipment':'emulation');
  const data=live.value;
  const tabs=[...(!operation?[['emulation','Эмуляция']]:[]),['equipment','Оборудование'],['maintenance','ТО и ресурс'],['stock',operation?'Запчасти участка':'Склад и закупки'],['alarms','События узлов']];
  return <div className="manufacturing-page scada-page" data-testid={operation?`scada-scope-${operation}`:'scada-global'}>
    {operation&&<section className="panel"><h2>Оборудование и ТО · {operationNames[operation]}</h2><p className="intro">Здесь показаны оборудование, датчики, обслуживание и события выбранного участка. Привязку можно задать явно или определять по связанному роботу.</p></section>}
    <div className="automation-tabs" role="group" aria-label={operation?'Показатели оборудования участка':'Разделы оборудования'}>{tabs.map(([id,label])=><button key={id} className={`button ${tab===id?'primary':'secondary'}`} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {tab==='emulation'&&!operation&&<Emulation/>}
    {live.error&&<p role="alert" className="connection-banner">Не удалось обновить данные: {live.error}. Сохранённые на экране значения могут быть устаревшими.</p>}
    {!data?<section className="panel">Загружаем оборудование…</section>:<>
      {tab!=='emulation'&&<div className="manufacturing-metrics">{[['Единицы оборудования',data.totals.assets],['Узлы',data.totals.components],['Открытые события',data.totals.alarms],['Дефицитные позиции',data.totals.shortages]].map(([label,value])=><section className="panel manufacturing-metric" key={label}><span>{label}</span><strong>{number(value)}</strong></section>)}</div>}
      {tab==='equipment'&&<Equipment data={data} changed={live.refresh}/>}
      {tab==='maintenance'&&<Maintenance data={data} changed={live.refresh}/>}
      {tab==='stock'&&(operation?<ScopedParts data={data}/>:<Warehouse data={data} changed={live.refresh}/>)}
      {tab==='alarms'&&<Alarms data={data} changed={live.refresh}/>}
    </>}
  </div>;
}

function ScopedParts({data}:{data:ScadaData}) {
  return <section className="panel"><h2>Запчасти для узлов участка</h2><p className="intro">Склад общий для всей установки. Потребность участка показана отдельно; остаток и дефицит относятся ко всему производству. Управление поступлениями и закупками доступно в разделе «Оборудование и ТО → Склад и закупки».</p>
    <div className="robot-table"><table><thead><tr><th>Деталь</th><th>Общий остаток</th><th>Нужно участку</th><th>Нужно всего</th><th>В заказе всего</th><th>Общий дефицит</th></tr></thead><tbody>{data.parts.map(p=><tr key={p.id}><td>{p.name}<small className="scada-subtext">{p.id}</small></td><td>{number(p.stock)} {p.unit}</td><td>{number(p.scope_needed)}</td><td>{number(p.needed)}</td><td>{number(p.on_order)}</td><td className={p.deficit?'alarm-text':''}>{number(p.deficit)}</td></tr>)}</tbody></table></div>
    {!data.parts.length&&<p className="small-note">Детали ещё не связаны с узлами этого участка. Укажите деталь для замены в настройках узла.</p>}
  </section>;
}

function Equipment({data,changed}:{data:ScadaData;changed:()=>void}) {
  const [selected,setSelected]=useState(''),[componentId,setComponentId]=useState('');
  const asset=data.assets.find(a=>a.id===selected)??data.assets[0];
  const components=data.components.filter(c=>c.asset_id===asset?.id);
  const component=components.find(c=>c.id===componentId)??components[0];
  return <>
    <section className="panel"><div className="panel-heading"><h2>Роботы и конвейеры</h2><span className="connection-tag">Показания оборудования</span></div><p className="intro">Узлы, датчики и регламенты вашей установки. Значения появляются после ввода показаний, загрузки CSV или подключения источника.</p>
      {!data.assets.length&&<p className="report-warning">Оборудование ещё не зарегистрировано. Добавьте робот или конвейер, затем его узлы. Данные симулятора не подставляются в датчики.</p>}
      <div className="equipment-list">{data.assets.map(a=><button key={a.id} className={`equipment-item ${asset?.id===a.id?'selected':''}`} onClick={()=>{setSelected(a.id);setComponentId('');}}><strong>{a.name}</strong><small>{a.id} · {a.section||'Участок не задан'}</small><Badge value={a.severity}/><small>{number(a.component_count)} узлов · {operationNames[a.operation]??'Не определено'}</small></button>)}</div>
      {asset&&<><h3>{asset.name} · карта узлов</h3>{asset.kind==='conveyor'&&<div className="scada-conveyor" aria-label="Узлы конвейера">{['drive','chain','take','track'].map(node=><button type="button" key={node} className="equipment-item" onClick={()=>{const found=components.find(c=>c.node===node);if(found)setComponentId(found.id);}}><strong>{nodeNames[node]}</strong><small>{components.filter(c=>c.node===node).length} узлов</small><span aria-hidden="true">{node==='chain'?'▰ ▰ ▰':node==='drive'?'⚙':node==='track'?'◎':'↔'}</span></button>)}</div>}
        <div className="robot-table"><table><thead><tr><th>Узел</th><th>Расположение</th><th>Состояние</th><th>Показания</th><th>Износ</th></tr></thead><tbody>{components.map(c=><tr key={c.id}><td><button className="button secondary compact" onClick={()=>setComponentId(c.id)}>{c.name}</button><small className="scada-subtext">{c.id}</small></td><td>{nodeNames[c.node]??c.node??'—'}</td><td><Badge value={c.severity}/></td><td><Badge value={c.connection}/></td><td>{number(c.wear_pct,1)} %</td></tr>)}</tbody></table></div>{!components.length&&<p className="small-note">Добавьте узлы этого оборудования: оси J1–J6, кабели, оснастку, привод или цепь конвейера.</p>}
      </>}
      {asset&&<details><summary>Привязать оборудование к автоматизации</summary><SaveForm key={`${asset.id}-${asset.revision}`} title={`Участок оборудования ${asset.id}`} button="Сохранить привязку участка" changed={changed} reset={false} submit={(f,id)=>request(`/scada/assets/${encodeURIComponent(asset.id)}/operation`,{method:'PUT',body:JSON.stringify({operation:txt(f,'operation')==='auto'?null:txt(f,'operation'),expected_revision:asset.revision,request_id:id})})}><Select title="Привязка к автоматизации" name="operation" items={operationOptions} defaultValue={asset.operation_configured??'auto'}/><p className="small-note">Текущий участок: {operationNames[asset.operation]}. {asset.operation_source==='explicit'?'Задан оператором.':asset.operation_source==='robot'?'Определён по телеметрии связанного робота.':asset.operation_source==='section'?'Определён по названию участка.':'Для автоматического определения недостаточно данных.'}</p></SaveForm></details>}
      {asset&&['robot','conveyor'].includes(asset.kind)&&components.length===0&&<><QuickAction label="Создать типовую структуру узлов" path={`/scada/assets/${encodeURIComponent(asset.id)}/template`} changed={changed}/><p className="small-note">Только структура: 23 узла робота или 13 узлов конвейера. Показания, ресурс и пороги необходимо настроить по вашему оборудованию.</p></>}
      <details><summary>Добавить оборудование</summary><SaveForm title="Новое оборудование" button="Добавить оборудование" changed={changed} submit={f=>post('/scada/assets',{id:txt(f,'id'),name:txt(f,'name'),kind:txt(f,'kind'),section:txt(f,'section'),robot_id:txt(f,'robot_id')||null,operation:txt(f,'operation')==='auto'?null:txt(f,'operation')})}><Input title="Код оборудования" name="id" required/><Input title="Название оборудования" name="name" required/><Select title="Тип оборудования" name="kind" items={[{id:'robot',name:'Робот'},{id:'conveyor',name:'Конвейер'},{id:'equipment',name:'Другое оборудование'}]}/><Input title="Участок" name="section"/><Select title="Направление автоматизации" name="operation" items={operationOptions} defaultValue={data.scope?.operation??'auto'}/><Input title="Идентификатор робота в телеметрии" name="robot_id"/></SaveForm></details>
      {!!data.assets.length&&<details><summary>Добавить узел и настроить контроль</summary><ComponentForm data={data} assetId={asset?.id} changed={changed}/></details>}
    </section>
    {component&&<ComponentDetail key={component.id} component={component} data={data} changed={changed}/>}
    <section className="panel"><h2>Загрузка показаний узлов</h2><p className="intro">Шаблон предназначен для отдельных осей и узлов конвейера. Файл может содержать узлы разных участков; фильтр участка ограничивает только показ на экране. Обычный CSV роботов продолжает загружаться в разделе «Данные и настройки». Для связи с узлом выберите поля робота при создании узла.</p><a href="/api/scada/template" download className="button secondary">Скачать шаблон узлов CSV</a><SaveForm title="Импорт узлов CSV" button="Загрузить показания" changed={changed} submit={f=>request('/scada/import',{method:'POST',body:f})}><label>CSV показаний узлов<input name="file" type="file" accept=".csv" required/></label></SaveForm></section>
  </>;
}

function ComponentForm({data,assetId,changed,existing}:{data:ScadaData;assetId?:string;changed:()=>void;existing?:Component}) {
  const [model,setModel]=useState(existing?.life_model??'none'),[rules,setRules]=useState<string[]>(existing?.thresholds.map((_,i)=>`saved-${i}`)??[]);
  const initial=(id:string)=>id.startsWith('saved-')?existing?.thresholds[Number(id.slice(6))]:undefined;
  const canWrite=useCanWrite();
  return <SaveForm title={existing?'Настройки узла':'Новый узел'} button={existing?'Сохранить настройки узла':'Добавить узел'} changed={changed} reset={false} submit={f=>{
    const thresholds=rules.map(id=>({metric:txt(f,id+'metric'),label:txt(f,id+'label'),unit:txt(f,id+'unit'),direction:txt(f,id+'direction'),warning:num(f,id+'warning'),alarm:num(f,id+'alarm'),hysteresis:num(f,id+'hysteresis')}));
    const robot_metric_map=Object.fromEntries(rules.filter(id=>txt(f,id+'source')).map(id=>[txt(f,id+'source'),txt(f,id+'metric')]));
    const config={id:txt(f,'id'),asset_id:txt(f,'asset_id'),name:txt(f,'name'),node:txt(f,'node'),kind:txt(f,'kind'),part_id:txt(f,'part_id')||null,part_quantity:num(f,'part_quantity'),life_model:model,rated_life:model==='none'?null:nullable(f,'rated_life'),initial_wear_pct:nullable(f,'initial_wear_pct'),specification:txt(f,'specification'),commissioned_at:txt(f,'commissioned_at')?new Date(txt(f,'commissioned_at')).toISOString():null,reference_temperature_c:nullable(f,'reference_temperature_c')??80,expected_interval_seconds:num(f,'expected_interval_seconds'),thresholds,robot_metric_map};
    if(existing?.commissioned_at&&model==='calendar'&&existing.last)config.commissioned_at=existing.commissioned_at;
    return existing?request(`/scada/components/${encodeURIComponent(existing.id)}`,{method:'PUT',body:JSON.stringify({config,expected_revision:existing.revision})}):post('/scada/components',config);
  }}>
    <Input title="Код узла" name="id" defaultValue={existing?.id} required/><Input title="Название узла" name="name" defaultValue={existing?.name} required/><Select title="Родительское оборудование" name="asset_id" items={data.assets} defaultValue={existing?.asset_id??assetId}/><Select title="Тип узла" name="kind" defaultValue={existing?.kind} items={Object.entries(kinds).map(([id,name])=>({id,name}))}/>
    <label>Расположение<select aria-label="Расположение" name="node" defaultValue={existing?.node}>{[...['J1','J2','J3','J4','J5','J6'].map(id=>[id,id]),...Object.entries(nodeNames)].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
    <Select title="Деталь для замены" name="part_id" items={data.part_catalog??data.parts} empty defaultValue={existing?.part_id??''}/><Input title="Количество деталей на замену" name="part_quantity" type="number" min={1} defaultValue={existing?.part_quantity??1} required/>
    <label>Модель ресурса<select aria-label="Модель ресурса" name="life_model" value={model} onChange={e=>setModel(e.target.value)}>{Object.entries(models).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
    {model!=='none'&&<><Input title={`Номинальный ресурс (${model==='cycles'?'циклы':model==='distance'?'км':model==='calendar'?'дни':'часы'})`} name="rated_life" type="number" min={0.001} step="any" defaultValue={existing?.rated_life??''} required/><Input title="Основание: паспорт или регламент" name="specification" defaultValue={existing?.specification} required/></>}
    <Input title="Подтверждённый исходный износ, % (пусто — неизвестен)" name="initial_wear_pct" type="number" min={0} max={100} step="any" defaultValue={existing?.initial_wear_pct??''}/>
    {model==='calendar'&&<Input title="Дата установки" name="commissioned_at" type="datetime-local" defaultValue={existing?.commissioned_at?new Date(new Date(existing.commissioned_at).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):''} required/>}
    {model==='thermal'&&<Input title="Опорная температура ресурса, °C" name="reference_temperature_c" type="number" defaultValue={existing?.reference_temperature_c??80} required/>}
    <Input title="Ожидаемый интервал показаний, секунд" name="expected_interval_seconds" type="number" min={1} max={86400} defaultValue={existing?.expected_interval_seconds??60} required/>
    <div className="scada-wide"><p className="small-note">Пороги задаются по документации оборудования. Поля load_ratio и speed_ratio — доли от номинала; lubrication_pct — обеспеченность смазкой, %. Формулы стенда являются настраиваемой инженерной оценкой.</p>
      {existing&&<p className="small-note">После начала истории параметры ресурса фиксируются. Название, датчики, пороги и связь с деталями можно менять; изменение записывается в аудит.</p>}
      {rules.map((id,index)=><div className="scada-rule" key={id}><h3>Показатель {index+1}</h3><div className="quality-form"><Input title={`Код показателя ${index+1}`} name={id+'metric'} defaultValue={initial(id)?.metric} required/><Input title={`Название показателя ${index+1}`} name={id+'label'} defaultValue={initial(id)?.label} required/><Input title={`Единица ${index+1}`} name={id+'unit'} defaultValue={initial(id)?.unit}/><Select title={`Направление порога ${index+1}`} name={id+'direction'} defaultValue={initial(id)?.direction} items={[{id:'high',name:'Превышение'},{id:'low',name:'Понижение'}]}/><Input title={`Порог внимания ${index+1}`} name={id+'warning'} type="number" step="any" defaultValue={initial(id)?.warning} required/><Input title={`Порог аварии ${index+1}`} name={id+'alarm'} type="number" step="any" defaultValue={initial(id)?.alarm} required/><Input title={`Гистерезис ${index+1}`} name={id+'hysteresis'} type="number" min={0} step="any" defaultValue={initial(id)?.hysteresis??0}/><label>Поле робота (необязательно)<select name={id+'source'} defaultValue={Object.entries(existing?.robot_metric_map??{}).find(([,dest])=>dest===initial(id)?.metric)?.[0]??''}><option value="">Отдельный датчик узла</option>{['joint_temperature_c','vibration_mm_s','motor_current_a','welding_current_a','hydraulic_pressure_bar','pneumatic_pressure_bar','paint_volume_l','electrode_count',...Array.from({length:6},(_,i)=>`joint_${i+1}_deg`)].map(s=><option key={s}>{s}</option>)}</select></label></div><button type="button" className="button secondary compact" onClick={()=>setRules(rules.filter(k=>k!==id))}>Убрать показатель {index+1}</button></div>)}
      <button type="button" className="button secondary" disabled={!canWrite||rules.length>=30} onClick={()=>setRules([...rules,uid()])}>Добавить показатель</button>
    </div>
  </SaveForm>;
}

function ComponentDetail({component:c,data,changed}:{component:Component;data:ScadaData;changed:()=>void}) {
  const [offset,setOffset]=useState(0);
  const history=useLive<{total:number;rows:{reading:Reading;origin:string}[]}>(`/scada/history?component_id=${encodeURIComponent(c.id)}&offset=${offset}`,5000);
  const keys=Array.from(new Set([...c.thresholds.map(r=>r.metric),...(c.life_model==='thermal'?['temperature_c']:c.life_model==='reducer'?['load_ratio','speed_ratio']:c.life_model==='chain'?['load_ratio','lubrication_pct']:[])]));
  return <section className="panel"><div className="panel-heading"><div><span className="eyebrow">{c.id} · {kinds[c.kind]}</span><h2>{c.name}</h2></div><Badge value={c.connection}/></div><p className="small-note">Последнее наблюдение: {date(c.last?.timestamp)}. {c.specification||'Регламент ресурса не задан.'}</p>
    <div className="arm-readings">{Object.entries(c.last?.metrics??{}).map(([key,value])=><div className="arm-reading" key={key}><span>{c.thresholds.find(r=>r.metric===key)?.label??key}</span><strong>{number(value,3)}</strong><small>{c.thresholds.find(r=>r.metric===key)?.unit}</small></div>)}</div>
    <div className="consumable-grid"><div className="consumable"><span>Расчётный износ</span><strong>{number(c.wear_pct,1)} %</strong>{c.wear_pct!==null&&<meter min={0} max={100} value={Math.min(100,c.wear_pct)}/>}</div><div className="consumable"><span>Оценка остаточного ресурса</span><strong>{number(c.remaining_hours,1)} ч</strong><small>По последнему интервалу работы</small></div><div className="consumable"><span>Расчётная дата ТО</span><strong>{day(c.due_date)}</strong><small>Не гарантия срока отказа</small></div></div>
    {c.gaps.map(g=><p className="report-warning" key={g}>{g}</p>)}
    <details><summary>Настройки этого узла</summary><ComponentForm key={c.id+':'+c.revision} data={data} existing={c} changed={changed}/></details>
    <details><summary>Внести измеренные показания</summary><SaveForm title="Показания узла" button="Сохранить показания" changed={()=>{changed();history.refresh();}} submit={(f,id)=>post('/scada/readings',{readings:[{record_id:id,component_id:c.id,timestamp:new Date(txt(f,'timestamp')).toISOString(),metrics:Object.fromEntries(keys.filter(k=>txt(f,'metric:'+k)!=='').map(k=>[k,num(f,'metric:'+k)])),runtime_hours:nullable(f,'runtime_hours'),total_cycles:nullable(f,'total_cycles'),distance_km:nullable(f,'distance_km')}]})}><Input title="Время показания узла" name="timestamp" type="datetime-local" defaultValue={localNow()} required/><Input title="Суммарная наработка, ч" name="runtime_hours" type="number" min={0} step="any"/><Input title="Суммарное число циклов" name="total_cycles" type="number" min={0} step="1"/><Input title="Суммарный пробег, км" name="distance_km" type="number" min={0} step="any"/>{keys.map(k=><Input key={k} title={c.thresholds.find(r=>r.metric===k)?.label??k} name={'metric:'+k} type="number" step="any"/>)}</SaveForm></details>
    <details><summary>История показаний ({history.value?.total??0})</summary><a href={`/api/scada/export?component_id=${encodeURIComponent(c.id)}`} className="button secondary" download>Выгрузить историю CSV</a>{history.error&&<p role="alert">{history.error}</p>}<div className="robot-table"><table><thead><tr><th>Время</th><th>Наработка, ч</th><th>Циклы</th><th>Пробег, км</th><th>Датчики</th></tr></thead><tbody>{history.value?.rows.map(({reading:r})=><tr key={r.record_id}><td>{date(r.timestamp)}</td><td>{number(r.runtime_hours,2)}</td><td>{number(r.total_cycles)}</td><td>{number(r.distance_km,2)}</td><td>{Object.entries(r.metrics).map(([k,v])=>`${k}: ${number(v,3)}`).join('; ')||'—'}</td></tr>)}</tbody></table></div><div className="automation-tabs"><button className="button secondary compact" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-100))}>Новее</button><button className="button secondary compact" disabled={!history.value||offset+100>=history.value.total} onClick={()=>setOffset(offset+100)}>Старее</button></div></details>
  </section>;
}

function Maintenance({data,changed}:{data:ScadaData;changed:()=>void}) {
  const [all,setAll]=useState(false);
  const components=[...data.components].sort((a,b)=>(a.due_date??'9999').localeCompare(b.due_date??'9999'));
  const tasks=all?data.tasks:data.tasks.filter(t=>t.status==='planned');
  return <><section className="panel"><h2>ТО и оценка ресурса</h2><p className="intro">Наработка, циклы, температура, нагрузка редукторов и смазка цепи учитываются по показаниям. Календарные интервалы отсчитываются от установки или выполненного обслуживания.</p><div className="robot-table"><table><thead><tr><th>Узел</th><th>Модель</th><th>Износ</th><th>Остаток</th><th>Дата ТО</th><th>Данные</th></tr></thead><tbody>{components.map(c=><tr key={c.id}><td>{c.name}<small className="scada-subtext">{c.id}</small></td><td>{models[c.life_model]}</td><td>{number(c.wear_pct,1)} %</td><td>{number(c.remaining_hours,1)} ч</td><td>{day(c.due_date)}</td><td><Badge value={c.connection}/>{c.gaps.map(g=><small key={g} className="scada-subtext">{g}</small>)}</td></tr>)}</tbody></table></div>{!components.length&&<p className="small-note">Добавьте узлы в разделе «Оборудование».</p>}
    {!!components.length&&<details><summary>Запланировать обслуживание</summary><SaveForm title="Новая работа ТО" button="Запланировать ТО" changed={changed} submit={(f,id)=>post('/scada/tasks',{id,component_id:txt(f,'component_id'),due_date:txt(f,'due_date'),note:txt(f,'note')})}><Select title="Узел для обслуживания" name="component_id" items={components}/><Input title="Плановая дата ТО" name="due_date" type="date" required/><Input title="Основание работы" name="note" required/></SaveForm></details>}
    <details><summary>Производственный календарь</summary><p className="small-note">Календарь общий для всех участков этой установки.</p><SaveForm title="Календарь ТО" button="Сохранить календарь" changed={changed} submit={f=>request('/scada/calendar',{method:'PUT',body:JSON.stringify({hours_per_day:num(f,'hours_per_day'),weekdays:f.getAll('weekdays').map(Number),holidays:txt(f,'holidays').split(/[\s,;]+/).filter(Boolean)})})}><Input title="Рабочих часов в сутки" name="hours_per_day" type="number" min={1} max={24} defaultValue={data.calendar.hours_per_day} required/><div className="scada-weekdays">{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map((day,i)=><label key={day}><input type="checkbox" name="weekdays" value={i} defaultChecked={data.calendar.weekdays.includes(i)}/>{day}</label>)}</div><Input title="Выходные даты (ГГГГ-ММ-ДД через запятую)" name="holidays" defaultValue={data.calendar.holidays.join(', ')}/></SaveForm></details>
    </section><section className="panel"><div className="panel-heading"><h2>Работы по обслуживанию</h2><button className="button secondary compact" onClick={()=>setAll(!all)}>{all?'Только план':'Показать завершённые'}</button></div><p className="small-note">Закрывайте работу после фактической замены или регламентного обслуживания. Указанная деталь будет списана со склада; показания датчиков и аварии сохранятся до нового подтверждающего измерения.</p>{tasks.map(t=><article key={t.id} className="scada-entry"><h3>{data.components.find(c=>c.id===t.component_id)?.name??t.component_id}</h3><p className="intro">{day(t.due_date)} · {t.note}</p><Badge value={t.status}/>{t.status==='planned'?<><details><summary>Зарегистрировать выполнение</summary><SaveForm title={`Выполнение ТО ${t.component_id}`} button="Завершить ТО и списать деталь" changed={changed} submit={f=>post(`/scada/tasks/${encodeURIComponent(t.id)}/complete`,{evidence:txt(f,'evidence'),reset_counters:f.get('reset_counters')==='on'})}><Input title="Акт выполненной работы" name="evidence" required/><label className="scada-checkbox"><input type="checkbox" name="reset_counters"/> Контроллер обнулил счётчики после замены</label></SaveForm></details><QuickAction label="Отменить работу" path={`/scada/tasks/${encodeURIComponent(t.id)}/cancel`} changed={changed}/></>:<p className="small-note">{t.completed_by??''} {t.completed_at?date(t.completed_at):''}</p>}</article>)}{!tasks.length&&<p className="small-note">Запланированных работ нет.</p>}</section><JournalPanel kind="task" operation={data.scope?.operation}/></>;
}

function QuickAction({label,path,changed}:{label:string;path:string;changed:()=>void}) {
  const canWrite=useCanWrite(),[busy,setBusy]=useState(false),[error,setError]=useState('');
  return <><button type="button" className="button secondary compact" disabled={!canWrite||busy} onClick={async()=>{setBusy(true);setError('');try{await post(path,{});changed();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Сохраняем…':label}</button>{error&&<p className="inline-error" role="alert">{error}</p>}</>;
}

function Warehouse({data,changed}:{data:ScadaData;changed:()=>void}) {
  return <><section className="panel"><h2>Запчасти и потребность</h2><p className="intro">Дефицит учитывает ближайшие ТО, минимальный запас и подтверждённые поставки. Предложения разных валют сравниваются отдельно. Заявки ведутся внутри системы; подтверждение поставщика и накладная вводятся по фактическим документам.</p><div className="robot-table"><table><thead><tr><th>Деталь</th><th>Остаток</th><th>Минимум</th><th>Нужно для ТО</th><th>В заказе</th><th>Дефицит</th><th>Предложение</th></tr></thead><tbody>{data.parts.map(p=><tr key={p.id}><td>{p.name}<small className="scada-subtext">{p.id}</small></td><td>{number(p.stock)} {p.unit}</td><td>{p.minimum}</td><td>{p.needed}</td><td>{p.on_order}</td><td className={p.deficit?'alarm-text':''}>{p.deficit}</td><td>{p.recommendations.map(r=><div key={r.currency}>{r.supplier} · {number(r.price_minor/100,2)} {r.currency}<small className="scada-subtext">{r.lead_workdays} раб. дн. · {r.reason}</small></div>)}{!p.recommendations.length&&'Нет действующих предложений'}</td></tr>)}</tbody></table></div>
    {!data.parts.length&&<p className="small-note">Склад пуст. Добавьте номенклатуру и зарегистрируйте фактический остаток.</p>}
    <details><summary>Добавить деталь</summary><SaveForm title="Новая деталь" button="Добавить деталь" changed={changed} submit={f=>post('/scada/parts',{id:txt(f,'id'),name:txt(f,'name'),unit:txt(f,'unit'),minimum:num(f,'minimum')})}><Input title="Артикул детали" name="id" required/><Input title="Название детали" name="name" required/><Input title="Единица учёта" name="unit" defaultValue="шт." required/><Input title="Минимальный запас" name="minimum" type="number" min={0} defaultValue={0} required/></SaveForm></details>
    {!!data.parts.length&&<><details><summary>Учесть приход или расход</summary><SaveForm title="Складская операция" button="Сохранить движение" changed={changed} submit={(f,id)=>post('/scada/stock',{record_id:id,part_id:txt(f,'part_id'),quantity:num(f,'quantity'),reason:txt(f,'reason')})}><Select title="Деталь на складе" name="part_id" items={data.parts}/><Input title="Количество (расход со знаком минус)" name="quantity" type="number" step="1" required/><Input title="Документ и основание движения" name="reason" required/></SaveForm></details>
    <details><summary>Добавить предложение поставщика</summary><SaveForm title="Предложение поставщика" button="Сохранить предложение" changed={changed} submit={(f,id)=>post('/scada/offers',{id,part_id:txt(f,'part_id'),supplier:txt(f,'supplier'),price_minor:Math.round(num(f,'price')*100),currency:txt(f,'currency'),lead_workdays:num(f,'lead_workdays'),valid_until:txt(f,'valid_until'),reference:txt(f,'reference')})}><Select title="Деталь в предложении" name="part_id" items={data.parts}/><Input title="Поставщик" name="supplier" required/><Input title="Цена за единицу" name="price" type="number" min={0} step="0.01" required/><Select title="Валюта" name="currency" items={['KZT','RUB','USD','EUR','CNY'].map(id=>({id,name:id}))}/><Input title="Поставка, рабочих дней" name="lead_workdays" type="number" min={0} max={730} required/><Input title="Предложение действует до" name="valid_until" type="date" required/><Input title="Номер предложения или источник цены" name="reference" required/></SaveForm></details></>}
    {!!data.offers.length&&<details><summary>Создать заявку на закупку</summary><SaveForm title="Новая заявка" button="Создать черновик заявки" changed={changed} submit={(f,id)=>post('/scada/orders',{id,offer_id:txt(f,'offer_id'),quantity:num(f,'quantity')})}><Select title="Предложение для закупки" name="offer_id" items={data.offers.map(o=>({id:o.id,name:`${o.part_id} · ${o.supplier} · ${number(o.price_minor/100,2)} ${o.currency} · до ${day(o.valid_until)}`}))}/><Input title="Количество в заявке" name="quantity" type="number" min={1} required/></SaveForm></details>}
    </section><section className="panel"><h2>Открытые заявки</h2>{!data.orders.length&&<p className="small-note">Открытых заявок нет.</p>}{data.orders.map(o=><article className="scada-entry" key={o.id}><h3>{o.part_id} · {o.supplier}</h3><p className="intro">{number(o.quantity)} ед. · {number(o.quantity*o.price_minor/100,2)} {o.currency} · Получено: {o.received} · Ожидается: {day(o.eta)}</p><Badge value={o.status}/>{o.status==='draft'?<SaveForm title={`Подтверждение заявки ${o.id}`} button="Учесть подтверждение поставщика" changed={changed} submit={f=>post(`/scada/orders/${encodeURIComponent(o.id)}/confirm`,{reference:txt(f,'reference')})}><Input title="Документ подтверждения поставщика" name="reference" required/></SaveForm>:<SaveForm title={`Приёмка заявки ${o.id}`} button="Принять на склад" changed={changed} submit={(f,id)=>post(`/scada/orders/${encodeURIComponent(o.id)}/receive`,{record_id:id,quantity:num(f,'quantity'),reference:txt(f,'reference')})}><Input title="Фактически получено" name="quantity" type="number" min={1} max={o.quantity-o.received} required/><Input title="Номер накладной" name="reference" required/></SaveForm>}<QuickAction label="Отменить неполученный остаток" path={`/scada/orders/${encodeURIComponent(o.id)}/cancel`} changed={changed}/></article>)}</section><JournalPanel kind="movement"/><JournalPanel kind="order"/></>;
}

function Alarms({data,changed}:{data:ScadaData;changed:()=>void}) {
  const [all,setAll]=useState(false), alarms=data.alarms.filter(a=>all||a.status!=='closed');
  return <><section className="panel"><div className="panel-heading"><h2>События и андон узлов</h2><button className="button secondary compact" onClick={()=>setAll(!all)}>{all?'Только открытые':'Показать закрытые'}</button></div><p className="intro">Подтверждение означает, что событие принято в работу. Оно закрывается после устранения причины по новым показаниям. Авария связанного узла блокирует запуск и повышение скорости через заводской шлюз; физический аварийный останов остаётся на контроллере.</p><div className="robot-table"><table><thead><tr><th>Время</th><th>Узел</th><th>Событие</th><th>Значение</th><th>Статус</th><th>Действие</th></tr></thead><tbody>{alarms.map(a=><tr key={a.id}><td>{date(a.opened_at)}</td><td>{a.component_name}<small className="scada-subtext">{a.component_id}</small></td><td>{a.label}<small className="scada-subtext">{status[a.severity]}</small></td><td>{number(a.value,3)}</td><td><Badge value={a.status}/>{a.recovered_at&&<small className="scada-subtext">Причина устранена: {date(a.recovered_at)}</small>}</td><td>{!a.acknowledged_at?<QuickAction label="Принять в работу" path={`/scada/alarms/${encodeURIComponent(a.id)}/acknowledge`} changed={changed}/>:date(a.acknowledged_at)}</td></tr>)}</tbody></table></div>{!alarms.length&&<p className="small-note">Открытых событий нет. Датчики без настроенных порогов не оцениваются автоматически.</p>}</section><JournalPanel kind="alarm" operation={data.scope?.operation}/></>;
}

function JournalPanel({kind,operation}:{kind:string;operation?:Operation}) {
  const [offset,setOffset]=useState(0), live=useLive<Journal>(`/scada/journal?kind=${kind}&offset=${offset}${operation?`&operation=${operation}`:''}`,5000);
  const title:Record<string,string>={movement:'Журнал движения деталей',order:'История заявок',task:'Полный журнал ТО',alarm:'Полный журнал событий'};
  return <section className="panel"><details><summary>{title[kind]} · {live.value?.total??0}</summary>{live.error&&<p role="alert">{live.error}</p>}<div className="robot-table"><table><thead><tr><th>Дата</th><th>Объект</th><th>Содержание</th></tr></thead><tbody>{live.value?.rows.map(r=><tr key={String(r.id)}><td>{date(String(r.timestamp??r.created_at??r.opened_at??''))}</td><td>{String(r.part_id??r.component_id??'')}</td><td>{String(r.reason??r.note??r.label??r.supplier??'')} {r.quantity!==undefined&&<span> · {number(r.quantity)} ед.</span>}{r.balance!==undefined&&<span> · Остаток {number(r.balance)}</span>}{r.status!==undefined&&<span> · {status[String(r.status)]??String(r.status)}</span>}</td></tr>)}</tbody></table></div><div className="automation-tabs"><button className="button secondary compact" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-100))}>Новее</button><button className="button secondary compact" disabled={!live.value||offset+100>=live.value.total} onClick={()=>setOffset(offset+100)}>Старее</button></div></details></section>;
}
